Add support for creating data movers
YaleSpinup/datasync-api pull request #3
Opened 2021-12-14 22:29 UTC by tenyo

2021-12-21 16:01 UTC, fishnix requested changes
Looks good!  I had a few comments and the rollback stuff needs tweaking.

2021-12-21 16:56 UTC, tenyo commented on api/tags.go
> +		if t.Key == "spinup:org" || t.Key == "spinup:spaceid" || t.Key == "spinup:type" || t.Key == "spinup:flavor" {
I changed it because if the `aws:` prefix above. Unless we wanna combine if with case

2021-12-21 20:39 UTC, tenyo commented on api/orchestration_movers.go
> +	out, err := o.rgClient.GetResourcesWithTags(ctx, []string{"datasync"}, filters)
haha, that actually works 👍 👍 👍 I can remove a bunch of code now 😸 
I couldn't find in the docs what the available resource types are (`service[:resourceType]`)

2021-12-21 20:42 UTC, fishnix commented on api/orchestration_movers.go
> +	out, err := o.rgClient.GetResourcesWithTags(ctx, []string{"datasync"}, filters)
yeah the docs on that stuff are not great, i think its if the ARN has the resourceType its usually supported

2022-01-03 17:42 UTC, fishnix approved these changes
looks good!! 👍

2022-01-03 19:23 UTC, merged